apiVersion: v1
kind: Service
metadata:
  name: k8s-fastapi-svc
spec:
  selector:
    app: {{.Values.deployment.fastapi.app}}
  ports:
    - port: {{.Values.service.fastapi.port}}
      protocol: TCP
      targetPort: {{.Values.service.fastapi.targetPort}}
---
apiVersion: v1
kind: Service
metadata:
  name: helm-fanginx-svc
spec:
  selector:
    app: {{.Values.deployment.nginx.app}}
  ports:
    - port: {{.Values.service.nginx.port}}
      protocol: TCP
      targetPort: {{.Values.service.nginx.targetPort}}
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-mariadb-svc
spec:
  selector:
    app: {{.Values.deployment.mariadb.app}}
  ports:
    - port: {{.Values.service.mariadb.port}}
      protocol: TCP
      targetPort: {{.Values.service.mariadb.targetPort}}